### ISSUE TITLE
When pasting using the dialog SCAYT's span is not removed

### ISSUE THREAD

**Issue by Reinmar** [WebSpellChecker/ckeditor-plugin-scayt#70] opened 2014-05-14 14:13 UTC
1. Enable SCAYT.
2. Place cursor in the middle of misspelled word.
3. Open paste dialog and type something. Close the dialog.
4. Inserted content splits the SCAYT's span so the result may be e.g.:
`<p><span>foo</span>bar<span>bom</span></p>`

The expected result is that span is removed before content is inserted as it happens when pasting using shortcut.

Reproduced on FF and Chrome. Perhaps on IE it's reproducible as well.

**Comment by WebSpellChecker** [comment] 2015-01-28 07:52
Fix for the issue is available in dev branch.

**Comment by WebSpellChecker** [comment] 2015-01-30 16:27
We're glad to inform that the fix is released in version 4.6.2. Fix for the issue is present in plugin and CORE parts and available in master and on hosting.

**Closed by WebSpellChecker** 2015-01-30 16:27 UTC
Labels: bug
