### ISSUE TITLE
Creating CKEditor in a loop with "scayt_autoStartup :true" turned on causes JS errors being thrown.

### ISSUE THREAD

**Issue by jswiderski** [WebSpellChecker/ckeditor-plugin-scayt#106] opened 2015-09-21 13:11 UTC
Hi,

1. Please see http://dev.ckeditor.com/ticket/13706.
2. Please download and use file _test.html
3. Observe that when creating more than one editor with "scayt_autoStartup :true", JS errors are thrown.

Result can be observed mainly in Chrome but with _test.html I have also got it in Firefox and IE11.

**Comment by WebSpellChecker** [comment] 2015-09-22 12:17
It is a duplicate of this issue: https://github.com/WebSpellChecker/ckeditor-plugin-scayt/issues/105
We're reviewing it.

**Closed by WebSpellChecker** 2015-09-22 12:17 UTC
Labels: duplicate

**Comment by WebSpellChecker** [comment] 2015-09-22 13:29
The issue has been already fixed in the SCAYT plug-in for CKEditor. To apply the fix the CKEditor should be rebuilt with new SCAYT plug-in. It'll be available in the CKEditor package after futher CKEditor's releases.
