### ISSUE TITLE
Inline styles are not continued when writing multiple lines of styled text.

### ISSUE THREAD

**Issue by jswiderski** [WebSpellChecker/ckeditor-plugin-scayt#125] opened 2016-03-14 16:00 UTC
Please see: http://dev.ckeditor.com/ticket/14450

1. Load full featured editor - http://ckeditor.com/demo#full
2. Clear editor contents with New Page button.
3. Enable SCAYT.
4. Select few inline styles (e.g. font-family, font-size and font-color) and start typing
5. Press Enter and start typing again
Result: Inline styles are not continued in the second line. The typed text is not styled.

Problem can only be reproduced with SCAYT turned on and only in Blink/Webkit browsers.

**Comment by WebSpellChecker** [comment] 2016-03-30 12:34
The issue is reported and fixed in the upcoming release of version 4.8.3. We'll update you when the fix is available.

**Comment by WebSpellChecker** [comment] 2016-04-05 11:18
The fix has been released.

**Closed by WebSpellChecker** 2016-04-05 11:18 UTC
Labels: bug
