### ISSUE TITLE
Dragging image into CKEditor triggers instant spellcheck of src

### ISSUE THREAD

**Issue by fasterforward** [WebSpellChecker/ckeditor-plugin-scayt#120] opened 2015-12-18 10:14 UTC
CKEditor version: 4.5.6
Scayt version: x64 4.8.1

When dragging images from file into CKEditor using the uploadimage addon (http://ckeditor.com/addon/uploadimage) and Scayt is enabled, Scayt will instant spellcheck the complete src of the image (base64). On the network tab of the browser you'll see al lot of requests being fired (scayt.js). Furthermore adding the img tag to the scayt_elementsToIgnore setting doesn't like to work.

Can be reproduced here:
http://sdk.ckeditor.com/samples/fileupload.html#uploading-dropped-and-pasted-images

**Comment by WebSpellChecker** [comment] 2015-12-21 13:11
We're planning to start the investigation and fixing next development sprint that is started on Monday (January 4, 2016). It should be released in the WebSpellChecker.net v 4.9 (February, 2016)

**Comment by WebSpellChecker** [comment] 2016-03-14 15:48
This is chromium and Blink like behavior for such a way to embed data. Such a behavior is described on chromium issue tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=155071. The number of requests could be reproduced with disabled SCAYT just clicking on drag-and-drop image on the previously mentioned page: http://sdk.ckeditor.com/samples/fileupload.html#uploading-dropped-and-pasted-images. So this is not network requests, it's just information.

SCAYT needs to work with DOM to remove its' markup correctly. Requests of base64 data are caused by chromium during these operations.

The issue is closed.

**Closed by WebSpellChecker** 2016-03-14 15:48 UTC
Labels: bug
