### ISSUE TITLE
IE10-IE9 support

### ISSUE THREAD

**Issue by jacekbogdanski** [WebSpellChecker/ckeditor-plugin-scayt#175] opened 2020-09-02 12:59 UTC
It seems like spell checking stopped working for older browsers. There is already a reported issue for IE8 - https://github.com/WebSpellChecker/ckeditor-plugin-scayt/issues/161, but currently, it also relates to IE9 and IE10.

Reproduction steps are almost identical:

1. Use system with Internet Explorer 9/10:
2. Open sample http://cdn.ckeditor.com/4.14.1/full-all/samples/
3. Try to enable SCAYT

![scayt](https://user-images.githubusercontent.com/10279586/91984171-6a8a1680-ed2c-11ea-9616-6889a5a4bfe7.gif)

The only option which works is WSC dialog, there is no console error or anything like that.

If these browsers are no longer supported, it would be great if you could show some information about it or disable spell checking button. Otherwise, it seems like the feature is broken.

**Comment by jshaptala** [comment] 2020-09-02 15:53
Discussed the details in the separate chat, Our team will try to reproduce the issue and get back with the status.

**Comment by jshaptala** [comment] 2020-09-04 13:47
Just to let you know that the problem with IE9-10 has been reproduced and the root problem has also been found. It will be fixed in our upcoming release – mid September. No changes to the plugin are needed. The problem is in the core app.

**Comment by jacekbogdanski** [comment] 2020-09-04 15:09
Thanks for the quick response, sounds great!

**Comment by jshaptala** [comment] 2020-09-18 20:49
Hi @jacekbogdanski, glad to inform you that yesterday we rolled out release v5.6.4 that restored the support of IE9-10 by SCAYT plugin.

Please note that I've renamed the issue, so now it is about support for IE9-10. There is a separate issue open for IE8 and it was already commented on. We are not going to fix it or provide support for IE8 further.

**Comment by f1ames** [comment] 2020-09-21 07:34
Thanks @jshaptala! :+1: :tada: 

@jacekbogdanski could you check on our side if it works fine in IE9-10? If so, I guess we could close this ticket.

**Comment by jshaptala** [comment] 2020-09-21 08:48
@f1ames, we've validated the fix on our side. Would you please confirm if this works for you as well?

**Comment by jacekbogdanski** [comment] 2020-09-21 10:16
@jshaptala fix works fine, I've tested it on IE9-10. Thanks for the help!

**Closed** 2020-09-21 10:22 UTC
Labels: resolution:fixed
