### ISSUE TITLE
Error thrown after enabling SCAYT

### ISSUE THREAD

**Issue by Tade0** [WebSpellChecker/ckeditor-plugin-scayt#111] opened 2015-11-19 13:45 UTC
### Steps to reproduce

Open CKEditor (hash: b34ea4de6106ce5513da723ba42c3ba52da7424a) with SCAYT plugin (hash: 54fcc98).
1. Open console.
2. Click "Spell Checker" button and choose "Enable SCAYT".
3. Start typing.
### Expected result

SCAYT is enabled without any warnings or errors.
### Actual result

Error: `Uncaught ReferenceError: multiLanguageMode is not defined` in `http://svc.webspellchecker.net/spellcheck31/lf/scayt3/ckscayt/ckscayt.js:37`
### Other details (browser, OS, CKEditor version, installed plugins)

Chrome 46, Android 4.4.2

**Comment by michaeldimoudis** [comment] 2016-02-25 05:26
We are getting this issue too on Android devices. Have you found a fix? We are seeing it's happening on Android 5.x users for us.

**Comment by WebSpellChecker** [comment] 2016-03-30 12:23
Could not reproduced. Could you please describe more clear steps and environment. Could it be reproduced here: http://www.ckeditor.com/demo ?

**Comment by artiq5** [comment] 2016-07-04 13:42
@Tade0 @michaeldimoudis Guys, do you have any updates on this? Coz we could not reproduced. Could you please describe more clear steps and environment. Could it be reproduced here: http://www.ckeditor.com/demo ?

**Comment by wsc-julia-shaptala** [comment] 2017-08-09 15:07
The issue is not reproducible with provided steps. Since there are no details which help us to reproduce it, we close the issue.

**Closed by wsc-julia-shaptala** 2017-08-09 15:07 UTC
Labels: question
