### ISSUE TITLE
SCAYT's spans leak into the clipboard and after pasting

### ISSUE THREAD

**Issue by Reinmar** [WebSpellChecker/ckeditor-plugin-scayt#104] opened 2015-08-04 10:44 UTC
I've been definitely able to reproduce this issue with Firefox, but I think that it may be also reproducible on other browsers.

To test:

1. Open http://cdn-source.ckeditor.com/4.5.1/standard-all/samples/
2. Type random letters in few words in the content.
3. Enable SCAYT. Incorrect words should be underlined.
4. Select the content by mouse or keyboard (but not by CTRL+A which somehow removes the spans).
5. Copy that content.
6. Paste it to a sample without ACF like http://cdn-source.ckeditor.com/4.5.1/standard-all/samples/old/magicline/magicline.html
7. See that pasted text includes spans and they are visible in the output:

```
<h1><span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="Hddello">Hddello</span> <span class="scayt-misspell-word" data-scayt-lang="en_US" data-scayt-word="wddorld">wddorld</span>!</h1>

<p>I&#39;m andd insddtance of <a href="http://ckeditor.com">CKEditor</a>.</p>
```

**Note** that depending on how the content was selected some spans disappear and some other not. 

The expected behaviour is that:

1. Spans are removed before they copy takes place. This is the preferred solution as it prevents those spans leaking anywhere (e.g. to an editor which doesn't have SCAYT plugin enabled).
2. Spans are removed on paste. This is a bit worse solution, because SCAYT plugin may not be enabled in certain editor and then spans won't be filtered out.

**Comment by Reinmar** [comment] 2015-08-04 10:44
Reported in http://dev.ckeditor.com/ticket/13607.

**Comment by Reinmar** [comment] 2015-08-04 10:48
Note – on Chrome and Safari it may happen that these spans are copied to but are filtered by the [paste filter](http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-pasteFilter). Since the paste filter may be disabled or configured differently, this would be still a bug.

**Comment by WebSpellChecker** [comment] 2015-08-07 15:30
We're in progress to review the benavior of with enable allowContent option. We'll get back with the results on Wednesday (August 12).

**Comment by WebSpellChecker** [comment] 2015-08-13 15:50
We confirm that this is the issue. It has been reported into our internal bug tracking system. Our Web Team currently is working on the solution. We're on the investigation stage and notify you when the status of the issue is changed.

**Comment by WebSpellChecker** [comment] 2015-09-03 09:30
Please be informed that the fix for the issue has been released and merged to the master branch.

**Closed by WebSpellChecker** 2015-09-03 09:30 UTC
Labels: bug
