### ISSUE TITLE
SCAYT or WSC polluting global page styles

### ISSUE THREAD

**Issue by deant** [WebSpellChecker/ckeditor-plugin-scayt#159] opened 2018-06-25 10:10 UTC
I am observing that CKeditor with the WSC and SCAYT plugins added is inserting the following line at the bottom of my page's `<head>`:

```
<link rel="stylesheet" type="text/css" href="http://svc.webspellchecker.net/spellcheck31/lf/scayt3/ckscayt/themes/classic-blue/all.css">
```

This would be bad enough given the potential for style definitions from this file to clash with my own (for example, this file defines rules for `.more-list`, `.button-holder`, `.i-icon`, and other such classnames that are not too unlikely to be used elsewhere), but it also defines the top-level tag rules:

```
textarea,input {
 font-family:inherit;
 font-size:inherit;
 line-height:inherit
}
```

Which are changing the appearance of all the input boxes on my page!
I'm not sure since when this behavior started...

_NOTE: Originally I posted this as a CKeditor4 bug (#2147), but they say it's nothing to do with them, and belongs either here or on the WSC bug tracker.  So this is a cross-repost to this repository.  If it's actually a WSC bug rather than a SCAYT bug, please let me know, and I'll post it there instead._ 

_NOTE: Might be related to bug https://github.com/WebSpellChecker/ckeditor-plugin-scayt/issues/157 ???_ 

## Provide detailed reproduction steps (if any)

1. Add a CKeditor instance to your page, which includes the WSC and SCAYT plugins.
2. Add a `<textarea>` or `<input>` to the page, unrelated to the CKeditor instance.
3. In my case, I load the page in an `<iframe>` contained in another page (not sure if this is important or not...).
3. Observe that after a brief delay (after CKeditor finishes loading), the `<textarea>` and `<input>` get re-styled. (Specifically, the size of the text changes).

### Expected result

CKeditor/WSC/SCAYT should **NOT** be adding stylesheets to the main page `<head>`, or if it does they should only include rules that are scoped using very unique id or classname selectors, unlikely to clash with anything else defined elsewhere.
...More likely, I expect this stylesheet is _supposed_ to be inserted into the CKeditor `<iframe>`, rather than into the containing page?  Note that this needs to work correctly even if the containing page is itself inside an `<iframe>` (as it is in my case).

### Actual result

_Styles are applied to page elements outside of the CKeditor!_

## Other details

* Browser:  **Firefox v60 x64**
* OS:  **Windows 10 x64**
* CKEditor version:  **4.6.2**
* Installed CKEditor plugins:  **a11yhelp, autogrow, basicstyles, blockquote, button, clipboard, colorbutton, colordialog, contextmenu, dialog, dialogui, elementspath, enterkey, entities, fakeobjects, filebrowser, find, floatingspace, floatpanel, font, format, horizontalrule, htmlwriter, image, imagebrowser, indent, indentblock, indentlist, justify, lineheight, link, list, listblock, liststyle, magicline, maximize, menu, menubutton, nbsp, noabp, onchange, panel, panelbutton, pastefromword, pastetext, popup, removeformat, resize, richcombo, scayt, selectall, showblocks, showborders, sourcearea, specialchar, symbol, tab, table, tableresize, tabletools, textselection, toolbar, undo, wsc, wysiwygarea**

**Comment by artem-abakumov** [comment] 2018-06-25 10:42
@deant Thank you for reporting this. We will check this issue on our-side and get back with comments.

**Comment by wsc-julia-shaptala** [comment] 2018-06-27 10:29
@deant,

We were able to reproduce the issue following your steps to reproduce. The fix for the issue is scheduled for our next release 5.0.2. Preliminary ETA is the end of July.

**Comment by deant** [comment] 2018-06-27 10:49
Great, thanks Julia.  Am I correct in assuming that the fix will be in online scripts/files only (by which I mean, those hosted by and loaded from [http://svc.webspellchecker.net/](http://svc.webspellchecker.net/)), and will therefore get applied automatically?  Or will we need to rebuild/update our server's CKeditor code to apply the fix?

**Comment by wsc-julia-shaptala** [comment] 2018-06-27 12:44
@deant, you are right. The update is related to the application core and will be applied automatically, as soon as we release the fix. No updates are required for the plugin itself.

**Comment by gaspo100** [comment] 2018-09-13 03:43
The current [css at http://svc.webspellchecker.net](http://svc.webspellchecker.net/spellcheck31/lf/scayt3/ckscayt/css/wsc.css) breaks rendering on our website. 

The `.red` class in the first rule `.red,.scayt-misspell-word,.spelling-problem,.wsc-spelling-problem` is the problem.  We use `.red` on many pages on our website and if ckeditor is on the page it causes elements to loose the red color and become underlined as if incorrectly spelled.

Could you please either remove `.red` from that rule or prefix it with `sc-` or simalar.

**Comment by artem-abakumov** [comment] 2018-09-13 06:37
@gaspo100 Thank you for contacting us. Our technical specialist will take a look on it immediately. Could you please share us with some public page when we can replicate the issue, screenshoots and steps to reproduce it. 

Kind regards,

**Comment by gaspo100** [comment] 2018-09-13 07:32
Basic example here, using ckeditor 4.8.0

[https://rtjcom.com/testcke.html](https://rtjcom.com/testcke.html)

**Comment by wiggydave10** [comment] 2018-09-14 10:36
Having the exact same problem as @gaspo100, we are using CKEditor V4.9.2, but seems to have only recently started occurring. Maybe this CSS file has changed or been updated.

**Comment by deant** [comment] 2018-09-14 11:17
At least in the CKeditor case, wouldn't it make sense to precede ALL scayt CSS rules with `.ckeditor` (or whatever class it is that CKeditor tags their editor instances with - I didn't actually look it up), so that they can't affect anything else on the page?  SCAYT is only supposed to affect the CKeditor contents, isn't it?  Or am I missing something here?

**Comment by wsc-julia-shaptala** [comment] 2018-09-14 11:33
Hi all,

The issue re-appeared after our recent release. We were able to reproduce it, and going to fix it by the beginning of the next week if the verification tests go well. We keep you posted.

Regards,

**Comment by artem-abakumov** [comment] 2018-09-18 10:55
@deant @gaspo100 @wiggydave10 The issue has been fixed as a part of WSC Release 5.2.0.4. Please re-check.

**Comment by gaspo100** [comment] 2018-09-19 04:55
Thank you. I can confirm the problem seem to be fixed on our web sites.

**Comment by artem-abakumov** [comment] 2018-09-19 05:51
@gaspo100 Good news! @deant @wiggydave10 and update on this?

**Comment by wiggydave10** [comment] 2018-09-19 08:17
@artem-abakumov all looks good our end. Thanks.

**Closed** 2018-09-19 15:50 UTC
Labels: bug

**Comment by epchristi** [comment] 2019-10-13 19:02
Will you be fixing this in version 4? This is happening on version 4.12.1 with the latest plugin.

**Comment by wsc-julia-shaptala** [comment] 2019-10-14 08:19
@epchristi, do you mean the issue reported in #58 (https://github.com/WebSpellChecker/ckeditor-plugin-wsc/issues/58)?
