### ISSUE TITLE
Lost focus when enabling SCAYT using keyboard.

### ISSUE THREAD

**Issue by adelura** [WebSpellChecker/ckeditor-plugin-scayt#71] opened 2014-05-16 10:36 UTC
Tested and confirmed in CKEditor 4.4.1 (since 4.3.1)
Browsers: All

1. Open http://ckeditor.com/demo.
2. Focus editor.
3. Press Alt + F10 to focus toolbar.
3. Navigate to SCAYT button using keyboard (arrows and tab).
4. Enable SCAYT using oppropriate button.

Actual result: focus is lost from editor.

**Comment by WebSpellChecker** [comment] 2015-01-26 08:03
The issue is fixed in SCAYT plugin (scayt-dev branch). It will be commited to master branch after release 4.6.2 in the end of January 2015

**Closed** 2015-01-26 08:03 UTC
Labels: bug

**Comment by adelura** [comment] 2015-01-26 08:05
Thank you :)

**Comment by WebSpellChecker** [comment] 2015-01-30 16:22
We're glad to inform you that the fix is committed into master branch.
